controller:
  batch: 10

reader:
  init:
    name: "torchvisionIO-custom-sorted"
    path_dir: "../data/stream3_v3"
saver:
  init:
    name: "pil"
    path_to_save: "./data/test"
    make_dirs: True
    ext: 'png'
    need_save: True    
search_engine:
  init:
    name: "torch-cam"
    threshold: 0.1
    type_background_substractor: "knn"
    model_name: "resnet18"
    